from AAAA_model_xin.feature import all_model_parm
# from ML.feature import all_model_parm
# from ML.feature import all_model_parm
import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.subplots(2,2)


# ax[0, 0].plot(range(1, 6), all_model_parm[0][0])
# ax[0, 0].plot(range(1, 6), all_model_parm[1][0])
# ax[0, 0].plot(range(1, 6), all_model_parm[2][0])
# ax[0, 0].plot(range(1, 6), all_model_parm[3][0])
# ax[0, 0].plot(range(1, 6), all_model_parm[4][0])
# ax[0, 0].plot(range(1, 6), all_model_parm[5][0])
# ax[0, 0].plot(range(1, 6), all_model_parm[6][0])
#
# ax[0, 1].plot(range(1,6), all_model_parm[0][1])
# ax[0, 1].plot(range(1,6), all_model_parm[1][1])
# ax[0, 1].plot(range(1,6), all_model_parm[2][1])
# ax[0, 1].plot(range(1,6), all_model_parm[3][1])
# ax[0, 1].plot(range(1,6), all_model_parm[4][1])
# ax[0, 1].plot(range(1,6), all_model_parm[5][1])
# ax[0, 1].plot(range(1,6), all_model_parm[6][1])
#
# ax[1, 0].plot(range(1,6), all_model_parm[0][2])
# ax[1, 0].plot(range(1,6), all_model_parm[1][2])
# ax[1, 0].plot(range(1,6), all_model_parm[2][2])
# ax[1, 0].plot(range(1,6), all_model_parm[3][2])
# ax[1, 0].plot(range(1,6), all_model_parm[4][2])
# ax[1, 0].plot(range(1,6), all_model_parm[5][2])
# ax[1, 0].plot(range(1,6), all_model_parm[6][2])
#
# ax[1, 1].plot(range(1,6), all_model_parm[0][3])
# ax[1, 1].plot(range(1,6), all_model_parm[1][3])
# ax[1, 1].plot(range(1,6), all_model_parm[2][3])
# ax[1, 1].plot(range(1,6), all_model_parm[3][3])
# ax[1, 1].plot(range(1,6), all_model_parm[4][3])
# ax[1, 1].plot(range(1,6), all_model_parm[5][3])
plt.ylim(0.85, 1)

fig.show()
plt.figure(figsize=(7, 7))
plt.subplot(221)
plt.title("accuracy")
plt.plot(range(1,6), all_model_parm[0][0], 'b-o', label='GBDT')
plt.plot(range(1,6), all_model_parm[1][0], 'g-o', label='RF')
plt.plot(range(1,6), all_model_parm[2][0], 'y-o', label='Adaboost')
plt.plot(range(1,6), all_model_parm[3][0], 'k-o', label='XGBoost')
plt.plot(range(1,6), all_model_parm[4][0], 'r-o', label='LightGBM')
# plt.plot(range(1,6), all_model_parm[5][0], 'k-o', label='SVM')
# plt.plot(range(1,6), all_model_parm[6][0], 'orange', label='XGBoost', linestyle='-', marker='o')
#plt.plot(range(1,6), all_model_parm[7][0], label='MLP', color="orange", linestyle='-', marker='^')
plt.ylim(0.85, 1)
plt.subplot(222)
plt.title("recall")
plt.plot(range(1,6), all_model_parm[0][1], 'b-o', label='GBDT')
plt.plot(range(1,6), all_model_parm[1][1], 'g-o', label='RF')
plt.plot(range(1,6), all_model_parm[2][1], 'y-o', label='Adaboost')
plt.plot(range(1,6), all_model_parm[3][1], 'k-o', label='XGBoost')
plt.plot(range(1,6), all_model_parm[4][1], 'r-o', label='LightGBM')
# plt.plot(range(1,6), all_model_parm[5][1], 'k-o', label='SVM')
# plt.plot(range(1,6), all_model_parm[6][1], 'orange', label='XGBoost', linestyle='-', marker='o')
#plt.plot(range(1,6), all_model_parm[7][1], label='MLP', color="orange", linestyle='-', marker='^')

plt.ylim(0.85, 1)
plt.subplot(223)
plt.title("precision")
plt.plot(range(1,6), all_model_parm[0][2], 'b-o', label='GBDT')
plt.plot(range(1,6), all_model_parm[1][2], 'g-o', label='RF')
plt.plot(range(1,6), all_model_parm[2][2], 'y-o', label='Adaboost')
plt.plot(range(1,6), all_model_parm[3][2], 'k-o', label='XGBoost')
plt.plot(range(1,6), all_model_parm[4][2], 'r-o', label='LightGBM')
# plt.plot(range(1,6), all_model_parm[5][2], 'k-o', label='SVM')
# plt.plot(range(1,6), all_model_parm[6][2], 'orange', label='XGBoost', linestyle='-', marker='o')
#plt.plot(range(1,6), all_model_parm[7][2], label='MLP', color="orange", linestyle='-', marker='^')

plt.ylim(0.85, 1)
plt.subplot(224)
plt.title("f1")
plt.plot(range(1,6), all_model_parm[0][3], 'b-o', label='GBDT')
plt.plot(range(1,6), all_model_parm[1][3], 'g-o', label='RF')
plt.plot(range(1,6), all_model_parm[2][3], 'y-o', label='Adaboost')
plt.plot(range(1,6), all_model_parm[3][3], 'k-o', label='XGBoost')
plt.plot(range(1,6), all_model_parm[4][3], 'r-o', label='LightGBM')
# plt.plot(range(1,6), all_model_parm[5][3], 'k-o', label='SVM')
# plt.plot(range(1,6), all_model_parm[6][3], 'orange', label='XGBoost', linestyle='-', marker='o')
#plt.plot(range(1,6), all_model_parm[7][3], label='MLP', color="orange", linestyle='-', marker='^')

plt.ylim(0.85, 1)
plt.legend(loc= 'best')
# plt.subplot(122)
# ha, lb = plt.get_legend_handles_labels()
# plt.figlegend(ha,lb,'right')
# legend(bbox_to_anchor=(1.0, 0.7))
# plt.axes(10,10,1,1)
plt.savefig("sly_model_zhibiao_300.png", dpi=300)
plt.savefig("sly_model_zhibiao_600.png", dpi=600)
plt.show()
